trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1

steps:
- script: 
    docker build -f Dockerfile -t rllib.azurecr.io/hello:world .
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
